# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'coinbase_order_book'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'mz'

model-paths: ["models"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  coinbase_order_book:
    sources:
      coinbase:
        +schema: source_coinbase
tests:
  coinbase_order_book:
    +store_failures: true 
    +schema: tests