version: 2

sources:
  - name: coinbase
    description: Data ingested from Coinbase
    schema: public_source_coinbase
    tables:
      - name: level2_channel
        description: '{{ doc("source_coinbase_level2_channel") }}'