version: 2

models:
  - name: stg_coinbase_order_book
    description: ""
    columns:
      - name: event_type
        description: ""
      - name: product_id
        description: ""
      - name: side
        description: ""
      - name: price
        description: ""
      - name: size
        description: ""
      - name: event_created_at
        description: ""
      - name: key
        description: ""