version: '3.7'
services:
  materialized:
    image: materialize/materialized:v0.26.0
    container_name: materialized
    command: -w1
    ports:
      - 6875:6875
  
  mzcli:
    image: materialize/cli
    container_name: mzcli
  
  dbt:
    image: materialize/dbt-materialize:v0.26.0
    container_name: dbt
    init: true
    ports:
      - 8000:8080
    volumes:
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
      - ./dbt/:/usr/app/dbt
    stdin_open: true
    tty: true
    depends_on:
      - materialized